name: Build Flet APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Java (Updated to v5)
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet jdatetime

      - name: Build APK
        run: |
          flet build apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: doosti-app-release
          path: build/apk/**/*.apk
          if-no-files-found: error
